### ISSUE TITLE
Use phantomjs-prebuilt instead of phantomjs

### ISSUE THREAD

**Issue by etamponi** [Two-Screen/noface#4]
The phantomjs npm module is deprecated (https://www.npmjs.com/package/phantomjs), they changed the name to phantomjs-prebuilt.

Is it possible to change the dependency?

Thanks

**Comment by stephank** [comment]
Whoops! Thanks for pointing that out, I'll get right on it!

**Comment by etamponi** [comment]
Thanks :)

PS: Your work is awesome, very lightweight and effective, exactly what I
was looking for!
Il 09 feb 2016 9:38 AM, "Stéphan Kochen" <notifications@github.com> ha
scritto:

**Comment by stephank** [comment]
Fixed in 0.1.4. Thanks again!
